---
apiVersion: v1
kind: Secret
metadata:
  name: moego-svc-message-v2-config
  namespace: test
stringData:
  config.yaml: |
    port: 9090
    db:
      moe_message:
        dsn: ${DB_MYSQL_USERNAME}:${DB_MYSQL_PASSWORD}@tcp(${DB_MYSQL_URL}:3306)/moe_message?parseTime=true
        max_open_connections: 100
        max_idle_connections: 10
        max_connection_lifetime: 1h
      message_v2_db:
        dsn: postgresql://${DB_POSTGRES_USERNAME}:${DB_POSTGRES_PASSWORD}@${DB_POSTGRES_URL}:5432/moego_message_v2
        max_open_connections: 100
        max_idle_connections: 10
    debug: false
    jaeger_url: http://jaeger-collector.jaeger.svc.cluster.local:14268/api/traces
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - sleep 10s
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
          - mountPath: /config
            name: config
      volumes:
        - name: config
          secret:
            secretName: moego-svc-message-v2-config
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - port: 9898
      name: http
      targetPort: 9898
      protocol: TCP
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: delegate-podinfo
  namespace: test
spec:
  hosts: []
  http:
    - name: default
      route:
        - destination:
            host: podinfo
            port:
              number: 9898
          weight: 100